spring:
  profiles:
    active:
      -dev
---
spring:
  profiles: dev
  application:
    name: vhr-config-dev
---
spring:
  profiles: test          # 测试环境
  application:
    name: vhr-config-dev
# 请保存为UTF-8格式